import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavBarComponent from "@/components/navBar";
import Footer from "@/components/home/footer";
import SkingenStats from "@/components/home/infoBrand";
import WhatsAppButton from "@/components/wpButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SkinGen Colombia",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
          <NavBarComponent/>
      {children}
      <div className="w-full h-full mx-auto">
          <SkingenStats />
        </div>
        <WhatsAppButton />
      <Footer/>
      </Providers>
      </body>
    </html>
  );
}
